### ISSUE TITLE
Declined or accepted invitations are not removed

### ISSUE THREAD

**Issue by leMaik** [Welfenlab/tutor-student#38] opened 2015-11-13 09:13 UTC
When the user accepts an invitation, their group is set correctly but the invitation is not removed. When the user declines an invitation, nothing happens.

**Comment by 5cript** [comment] 2015-11-13 14:39
This is strange, because I cannot reproduce it with tests.

**Comment by 5cript** [comment] 2015-11-13 14:41
#36 is basically the same.
... I will look into this once more, but its still strange.

**Comment by 5cript** [comment] 2015-11-13 15:36
Duplicate of #36 - no also closed.

**Closed by 5cript** 2015-11-13 15:36 UTC
Labels: bug, server
