### ISSUE TITLE
Show no previous exercises if there is none

### ISSUE THREAD

**Issue by LittleHelicase** [Welfenlab/tutor-student#66] opened 2016-03-11 14:03 UTC
Currently the overview page shows a previous exercise even if there is none.

**Comment by leMaik** [comment] 2016-03-14 22:42
I can't reproduce this. It displays "Sie haben noch keine Abgaben." for me, as expected.

**Comment by leMaik** [comment] 2016-03-18 15:25
Closed as I still can't reproduce this. :cry:

**Closed by leMaik** 2016-03-18 15:25 UTC
Labels: bug, in progress
